# Generated by Django 5.1.8 on 2025-04-15 03:24

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_can_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
