# Generated by Django 5.1.8 on 2025-04-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
